/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerArquivoCampeao;
import javax.swing.JOptionPane;
import model.Campeao;

/**
 *
 * @author Taynara Garcia Teixeira
 */
public class TelaCampeao extends javax.swing.JFrame {
    
    ControllerArquivoCampeao controle = new ControllerArquivoCampeao();
    Campeao campeao = new Campeao();

    /**
     * Creates new form TelaCampeao
     */
    public TelaCampeao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonSairUser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelFuncao = new javax.swing.JLabel();
        jTextFieldNomeCamp = new javax.swing.JTextField();
        jTextFieldHabilidade = new javax.swing.JTextField();
        jLabelHabilidade = new javax.swing.JLabel();
        jLabelDificuldade = new javax.swing.JLabel();
        jComboBoxDificuldade = new javax.swing.JComboBox<>();
        jComboBoxFuncao = new javax.swing.JComboBox<>();
        jButtonGravar = new javax.swing.JButton();
        jButtonSalvarEdicao = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Campeão");
        setPreferredSize(new java.awt.Dimension(646, 411));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel1.setText("CAMPEÃO");
        jLabel1.setMaximumSize(new java.awt.Dimension(382, 41));
        jLabel1.setMinimumSize(new java.awt.Dimension(382, 41));
        jLabel1.setPreferredSize(new java.awt.Dimension(382, 41));

        ButtonSairUser.setBackground(new java.awt.Color(0, 51, 51));
        ButtonSairUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonSairUser.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSairUser.setText("Voltar");
        ButtonSairUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairUserActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");
        jLabelNome.setMaximumSize(new java.awt.Dimension(30, 36));
        jLabelNome.setMinimumSize(new java.awt.Dimension(30, 36));

        jLabelFuncao.setText("Função:");

        jLabelHabilidade.setText("Habilidade:");

        jLabelDificuldade.setText("Dificuldade:");
        jLabelDificuldade.setPreferredSize(new java.awt.Dimension(105, 20));

        jComboBoxDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a dificuldade", "Fácil", "Média", "Alta" }));

        jComboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a função", "Assassino", "Mago", "Lutador", "Atirador", "Tanque", "Suporte" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHabilidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFuncao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextFieldNomeCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDificuldade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jButtonGravar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonGravar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGravar.setText("Gravar");
        jButtonGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGravarMouseClicked(evt);
            }
        });
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonSalvarEdicao.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSalvarEdicao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvarEdicao.setText("Salvar Alteração");
        jButtonSalvarEdicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarEdicaoMouseClicked(evt);
            }
        });
        jButtonSalvarEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEdicaoActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSairUser)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarEdicao)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSairUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(662, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSairUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairUserActionPerformed
        TelaHome home = new TelaHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonSairUserActionPerformed

    private void jButtonGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGravarMouseClicked
        try {
            Campeao novoCampeao = new Campeao();

            novoCampeao.setNome(jTextFieldNomeCamp.getText());
            novoCampeao.setFuncao(String.valueOf(jComboBoxFuncao.getSelectedItem()));
            novoCampeao.setHabilidade(jTextFieldHabilidade.getText());  
            novoCampeao.setDificuldade(String.valueOf(jComboBoxDificuldade.getSelectedItem()));
            
            // faz a validação dos dados. Verefica se os campos estão vazios
            if ((jTextFieldNomeCamp.getText().isEmpty()) || (jTextFieldHabilidade.getText().isEmpty()) ) {
                JOptionPane.showMessageDialog(this, "Os campos não podem retornar vazios");
            }
            
            controle.gravarCampeao(novoCampeao);
            JOptionPane.showMessageDialog(this, "Campeão salvo com sucesso em campeões.obj!");

            // limpa os campos novamente
            jTextFieldNomeCamp.setText("");
            jComboBoxFuncao.setSelectedItem("Selecione a função");
            jTextFieldHabilidade.setText("");
            jComboBoxDificuldade.setSelectedItem("Selecione a dificuldade");

        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ERRO AO CADASTRAR CAMPEÃO!");
        }
    }//GEN-LAST:event_jButtonGravarMouseClicked

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonSalvarEdicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarEdicaoMouseClicked
        try {
            Campeao campeaoAtualizado = new Campeao();
            
            campeaoAtualizado.setNome(jTextFieldNomeCamp.getText());
            campeaoAtualizado.setFuncao(String.valueOf(jComboBoxFuncao.getSelectedItem()));
            campeaoAtualizado.setHabilidade(jTextFieldHabilidade.getText());
            campeaoAtualizado.setDificuldade(String.valueOf(jComboBoxDificuldade.getSelectedItem()));

            // Verifica se os campos estão preenchidos corretamente
            if (jTextFieldNomeCamp.getText().isEmpty() ||
                jTextFieldHabilidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Os campos não podem ser vazios!");
                return;
            }

            // Chama o método de atualização
            controle.atualizarCampeao(campeaoAtualizado);
            JOptionPane.showMessageDialog(this, "Campeão atualizado com sucesso!");

            // Limpa os campos após a atualização
            jTextFieldNomeCamp.setText("");
            jComboBoxFuncao.setSelectedItem("Selecione a função");
            jTextFieldHabilidade.setText("");
            jComboBoxDificuldade.setSelectedItem("Selecione a dificuldade");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar campeão " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarEdicaoMouseClicked

    private void jButtonSalvarEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarEdicaoActionPerformed

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
        jTextFieldNomeCamp.setText("");   
        jComboBoxFuncao.setSelectedItem("Selecione a função");
        jTextFieldHabilidade.setText("");
        jComboBoxDificuldade.setSelectedItem("Selecione a dificuldade");
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCampeao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCampeao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSairUser;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonSalvarEdicao;
    private javax.swing.JComboBox<String> jComboBoxDificuldade;
    private javax.swing.JComboBox<String> jComboBoxFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDificuldade;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelHabilidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldHabilidade;
    private javax.swing.JTextField jTextFieldNomeCamp;
    // End of variables declaration//GEN-END:variables

    void recebeDadosCampeao(Campeao campeaoSelect) {
        jTextFieldNomeCamp.setText(campeaoSelect.getNome());
        jComboBoxFuncao.setSelectedItem(campeaoSelect.getFuncao());
        jTextFieldHabilidade.setText(campeaoSelect.getHabilidade());
        jComboBoxDificuldade.setSelectedItem(campeaoSelect.getDificuldade());
    }
}
