/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.TelaJogador;
import view.TelaCampeao;
import view.TelaPartidas;
import view.TelaBuscarJogador;
import view.TelaBuscarCampeao;
import view.TelaBuscarPartidas;

/**
 *
 * @author Taynara Garcia Teixeira
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ButtonJogadores = new javax.swing.JButton();
        ButtonCampeoes = new javax.swing.JButton();
        ButtonBuscarJogador = new javax.swing.JButton();
        ButtonPartidas1 = new javax.swing.JButton();
        ButtonBuscarCampeoes = new javax.swing.JButton();
        ButtonBuscarPartidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(0, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        ButtonJogadores.setBackground(new java.awt.Color(0, 51, 51));
        ButtonJogadores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonJogadores.setForeground(new java.awt.Color(255, 255, 255));
        ButtonJogadores.setText("Jogadores");
        ButtonJogadores.setBorderPainted(false);
        ButtonJogadores.setIconTextGap(2);
        ButtonJogadores.setMargin(new java.awt.Insets(2, 10, 2, 10));
        ButtonJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJogadoresActionPerformed(evt);
            }
        });

        ButtonCampeoes.setBackground(new java.awt.Color(0, 51, 51));
        ButtonCampeoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCampeoes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCampeoes.setText("Campeões");
        ButtonCampeoes.setBorderPainted(false);
        ButtonCampeoes.setIconTextGap(3);
        ButtonCampeoes.setMargin(new java.awt.Insets(2, 10, 3, 10));
        ButtonCampeoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCampeoesActionPerformed(evt);
            }
        });

        ButtonBuscarJogador.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBuscarJogador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarJogador.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuscarJogador.setText("Buscar Jogadores");
        ButtonBuscarJogador.setAlignmentY(0.3F);
        ButtonBuscarJogador.setBorderPainted(false);
        ButtonBuscarJogador.setIconTextGap(2);
        ButtonBuscarJogador.setMargin(new java.awt.Insets(2, 10, 3, 10));
        ButtonBuscarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarJogadorActionPerformed(evt);
            }
        });

        ButtonPartidas1.setBackground(new java.awt.Color(0, 51, 51));
        ButtonPartidas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonPartidas1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPartidas1.setText("Partidas");
        ButtonPartidas1.setBorderPainted(false);
        ButtonPartidas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPartidas1ActionPerformed(evt);
            }
        });

        ButtonBuscarCampeoes.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBuscarCampeoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarCampeoes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuscarCampeoes.setText("Buscar Campeões");
        ButtonBuscarCampeoes.setAlignmentY(0.3F);
        ButtonBuscarCampeoes.setBorderPainted(false);
        ButtonBuscarCampeoes.setIconTextGap(2);
        ButtonBuscarCampeoes.setMargin(new java.awt.Insets(2, 10, 3, 10));
        ButtonBuscarCampeoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarCampeoesActionPerformed(evt);
            }
        });

        ButtonBuscarPartidas.setBackground(new java.awt.Color(0, 51, 51));
        ButtonBuscarPartidas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuscarPartidas.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBuscarPartidas.setText("Buscar Partidas");
        ButtonBuscarPartidas.setBorderPainted(false);
        ButtonBuscarPartidas.setIconTextGap(2);
        ButtonBuscarPartidas.setMargin(new java.awt.Insets(2, 10, 3, 10));
        ButtonBuscarPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarPartidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBuscarJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCampeoes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonBuscarCampeoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPartidas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBuscarPartidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonJogadores)
                    .addComponent(ButtonCampeoes)
                    .addComponent(ButtonPartidas1)
                    .addComponent(ButtonBuscarJogador)
                    .addComponent(ButtonBuscarCampeoes)
                    .addComponent(ButtonBuscarPartidas))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lol.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(750, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJogadoresActionPerformed
        TelaJogador telajogadores = new TelaJogador();
        telajogadores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonJogadoresActionPerformed

    private void ButtonCampeoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCampeoesActionPerformed
        TelaCampeao telacampeoes = new TelaCampeao();
        telacampeoes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCampeoesActionPerformed

    private void ButtonBuscarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarJogadorActionPerformed
        TelaBuscarJogador telaBuscaJog = new TelaBuscarJogador();
        telaBuscaJog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBuscarJogadorActionPerformed

    private void ButtonPartidas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPartidas1ActionPerformed
        TelaPartidas telapartida = new TelaPartidas();
        telapartida.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonPartidas1ActionPerformed

    private void ButtonBuscarCampeoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarCampeoesActionPerformed
        TelaBuscarCampeao telaBuscaCamp = new TelaBuscarCampeao();
        telaBuscaCamp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBuscarCampeoesActionPerformed

    private void ButtonBuscarPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarPartidasActionPerformed
        TelaBuscarPartidas telaBuscaPart = new TelaBuscarPartidas();
        telaBuscaPart.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonBuscarPartidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscarCampeoes;
    private javax.swing.JButton ButtonBuscarJogador;
    private javax.swing.JButton ButtonBuscarPartidas;
    private javax.swing.JButton ButtonCampeoes;
    private javax.swing.JButton ButtonJogadores;
    private javax.swing.JButton ButtonPartidas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
